### ISSUE TITLE
Config difficult to use on Apple II+ keyboard

### ISSUE THREAD

**Issue by JamieB226** [FujiNetWIFI/fujinet-config#86]
The Apple II config program prompts the user to use keys (up, down, tab) that don't exist on an Apple II+ keyboard.  The only way to select disks is via the web interface

**Comment by JamieB226** [comment]
This is the default Apple II+ keyboard.  This could be resolved by adding a second key binding to the config utility which exists on this keyboard.

![20240727_211747](https://github.com/user-attachments/assets/78bbdc22-bfa1-4f2d-8233-de778223cbf4)

**Comment by mozzwald** [comment]
Do you have any recommendations? Current key binding are listed in https://github.com/FujiNetWIFI/fujinet-config/blob/main/src/apple2/input.c

**Comment by JamieB226** [comment]
I don't have a strong preference.  I could work with A (up) and Z (down).  I'm not sure if you can move between servers and drives with the up/down keys.  If so, those two may be sufficient.  If not, maybe a chord of CTRL-D.  I'm not sure if that introduces additional complexity.

**Comment by mozzwald** [comment]
Looking at the code, it appears  LEFT and RIGHT are used in addition to UP and DOWN in some places. So you should be able to use those keys when selecting a host at least. Is this not working on the main hosts screen? On IIe and up, TAB is used to jump from HOSTS to DRIVES so that would need to be added as a different key for II/II+ (maybe T ?).

https://github.com/FujiNetWIFI/fujinet-config/blob/ea61fb64e1d7ffdd18d11e581d94b1173f5625fd/src/apple2/input.c#L480

**Comment by JamieB226** [comment]
Left/right can work as up/down in some places, but in some places, it drills in/out of whatever is selected instead of doing up/down.  I'm fine with T for TAB.

**Comment by JamieB226** [comment]
As suggested in the Discord, you can use Ctrl-J, Ctrl-K, and Ctrl-I in place of up/down/tab.  It's not obvious from the config interface

**Comment by mozzwald** [comment]
i've added the ability to use IJKM for navigation and T for TAB. A message noting this is displayed on the main hosts/devices screen for Apple II/II+ machines

Fixed in d64378d, thanks for reporting!
